name: William Vo
favicon: null
layout_spectrum: 0.9130274106282741
typography_spectrum: 0.9152457346208394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9819852670188993
  lightness: 0.33983341767452657
  saturation: 0.37785424618050456
  rhythmicContrast: 0.7901904950849712
purpose: []
